name: Deploy WordPress to VPS

on:
  push:
    branches:
      - main  # Branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H mywordpress.ddns.net >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Dependencies and Build
        run: |
          sudo apt-get update
          sudo apt-get install php-cli php-fpm php-mysql -y

      - name: Deploy to VPS
        run: |
          # Securely transfer files to VPS
          scp -o StrictHostKeyChecking=no -r ./var/www/html/wordpress/newwordpress/* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:/var/www/html/wordpress/newwordpress

      - name: Cleanup
        run: |
          # cleanup steps
